### ISSUE TITLE
Error: no existe el modulo mercadopago

### ISSUE THREAD

**Issue by guzzi235** [ctmil/boton_mercadopago#1]
Lo quiero instalar pero me sale error: no existe el modulo mercadopago
aclaro que lo intento instalar como un modulo desde una 
carpeta extras/ incorporada en addons path, pero cuando actualizo la lista de modulos locales 
me sale el error de dependencia, tengo instalado el modulo payment_mercadopago.

**Comment by csrocha** [comment]
@guzzi235 , veo que has logrado hacer funcionar el módulo. Cierro el issue.
